services:
  digi-shaker:
    container_name: digi-shaker
    image: ghcr.io/1-felix/digi-shaker:latest
    ports:
      - "3982:3000"
    volumes:
      - .volumes/data:/app/data
    environment:
      - ESP32_HOST=192.168.0.82
      # - ESP32_PORT=81
      # - PORT=3000
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    driver: bridge
